"""
GET /api/v1/hotspots

Returns HDBSCAN cluster data with persistence scores.

Query params:
  - bbox: "lat_min,lng_min,lat_max,lng_max"  (optional)
  - date_from: YYYY-MM-DD  (optional)
  - date_to:   YYYY-MM-DD  (optional)
  - min_persistence: float 0-1  (optional, default 0.0)
  - limit: int (default 50)
"""

import json
import logging
from datetime import date
from pathlib import Path
from typing import Optional

import polars as pl
from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

logger = logging.getLogger(__name__)
router = APIRouter()

BASE_DIR = Path(__file__).resolve().parents[3]
FEATURE_STORE = BASE_DIR / "data" / "processed" / "clustered_feature_store.parquet"
PERSISTENCE_PATH = BASE_DIR / "data" / "processed" / "cluster_persistence.parquet"


# ── Response models ───────────────────────────────────────────────────────────

class OffenceBreakdown(BaseModel):
    offence_type: str
    count: int


class HotspotResponse(BaseModel):
    cluster_id: int
    centroid_lat: float
    centroid_lng: float
    violation_count: int
    mean_cluster_probability: float
    cluster_persistence_score: float
    hotspot_type: str           # "structural" | "moderate" | "transient"
    top_offence_types: list[OffenceBreakdown]
    geometry: dict              # GeoJSON Point


# ── Helpers ───────────────────────────────────────────────────────────────────

def _load_clustered_data(
    bbox: Optional[str],
    date_from: Optional[date],
    date_to: Optional[date],
) -> pl.DataFrame:
    if not FEATURE_STORE.exists():
        raise HTTPException(status_code=503, detail="Feature store not found. Run preprocessing pipeline first.")

    df = pl.read_parquet(FEATURE_STORE)

    # Must have cluster_id — generated by hdbscan_model.py run
    if "cluster_id" not in df.columns:
        raise HTTPException(status_code=503, detail="cluster_id column missing. Run HDBSCAN training first.")

    # Filter noise
    df = df.filter(pl.col("cluster_id") >= 0)

    # BBox filter
    if bbox:
        try:
            lat_min, lng_min, lat_max, lng_max = [float(x) for x in bbox.split(",")]
        except ValueError:
            raise HTTPException(status_code=400, detail="bbox must be 'lat_min,lng_min,lat_max,lng_max'")
        df = df.filter(
            pl.col("latitude").is_between(lat_min, lat_max)
            & pl.col("longitude").is_between(lng_min, lng_max)
        )

    # Date filters
    if date_from:
        df = df.filter(pl.col("created_datetime").dt.date() >= date_from)
    if date_to:
        df = df.filter(pl.col("created_datetime").dt.date() <= date_to)

    return df


def _get_top_offences(df_cluster: pl.DataFrame, n: int = 3) -> list[OffenceBreakdown]:
    """Extract top N offence types from violation_type column (JSON array string)."""
    if "primary_violation_type" in df_cluster.columns:
        # Layer 2 may have exploded this into a cleaned column
        col = "primary_violation_type"
        counts = (
            df_cluster
            .filter(pl.col(col).is_not_null())
            .group_by(col)
            .agg(pl.count("id").alias("count"))
            .sort("count", descending=True)
            .head(n)
        )
        return [
            OffenceBreakdown(offence_type=row["primary_violation_type"], count=row["count"])
            for row in counts.to_dicts()
        ]
    elif "violation_type" in df_cluster.columns:
        # Raw JSON array string — parse first element as proxy
        offence_counts: dict[str, int] = {}
        for raw in df_cluster["violation_type"].to_list():
            if raw is None:
                continue
            try:
                types = json.loads(raw) if isinstance(raw, str) else raw
                if isinstance(types, list):
                    for t in types:
                        offence_counts[str(t)] = offence_counts.get(str(t), 0) + 1
                else:
                    offence_counts[str(types)] = offence_counts.get(str(types), 0) + 1
            except (json.JSONDecodeError, TypeError):
                offence_counts[str(raw)] = offence_counts.get(str(raw), 0) + 1

        sorted_offences = sorted(offence_counts.items(), key=lambda x: x[1], reverse=True)[:n]
        return [OffenceBreakdown(offence_type=k, count=v) for k, v in sorted_offences]
    return []


def _hotspot_type(score: float) -> str:
    if score > 0.7:
        return "structural"
    elif score > 0.3:
        return "moderate"
    return "transient"


# ── Core query logic (plain callable — safe for both REST and GraphQL) ────────

def _query_hotspots(
    bbox: Optional[str] = None,
    date_from: Optional[date] = None,
    date_to: Optional[date] = None,
    min_persistence: float = 0.0,
    limit: int = 50,
) -> list[HotspotResponse]:
    """
    Shared hotspot query logic. No FastAPI Query() wrappers — plain Python
    defaults only, so this can be called directly (e.g. from GraphQL
    resolvers in backend/api/graphql/schema.py) as well as from the REST
    route below.
    """
    df = _load_clustered_data(bbox, date_from, date_to)

    # Load persistence scores and join if available
    persistence_col = "cluster_persistence_score"
    if persistence_col not in df.columns:
        if PERSISTENCE_PATH.exists():
            # Can't join grid-level here efficiently — use 0.0 as fallback
            logger.warning("cluster_persistence_score not in feature store — defaulting to 0.0")
        df = df.with_columns(pl.lit(0.0).alias(persistence_col))

    # Aggregate per cluster
    agg = (
        df.group_by("cluster_id")
        .agg([
            pl.col("latitude").mean().alias("centroid_lat"),
            pl.col("longitude").mean().alias("centroid_lng"),
            pl.count("id").alias("violation_count"),
            pl.col("cluster_probability").mean().alias("mean_cluster_probability"),
            pl.col(persistence_col).mean().alias("cluster_persistence_score"),
        ])
        .filter(pl.col("cluster_persistence_score") >= min_persistence)
        .sort("violation_count", descending=True)
        .head(limit)
    )

    results: list[HotspotResponse] = []
    for row in agg.to_dicts():
        cid = row["cluster_id"]
        cluster_rows = df.filter(pl.col("cluster_id") == cid)
        top_offences = _get_top_offences(cluster_rows)
        persist_score = float(row["cluster_persistence_score"])

        results.append(HotspotResponse(
            cluster_id=cid,
            centroid_lat=float(row["centroid_lat"]),
            centroid_lng=float(row["centroid_lng"]),
            violation_count=int(row["violation_count"]),
            mean_cluster_probability=float(row["mean_cluster_probability"]),
            cluster_persistence_score=persist_score,
            hotspot_type=_hotspot_type(persist_score),
            top_offence_types=top_offences,
            geometry={
                "type": "Point",
                "coordinates": [float(row["centroid_lng"]), float(row["centroid_lat"])],
            },
        ))

    return results


# ── Route ─────────────────────────────────────────────────────────────────────

@router.get("/hotspots", response_model=list[HotspotResponse])
def get_hotspots(
    bbox: Optional[str] = Query(None, description="lat_min,lng_min,lat_max,lng_max"),
    date_from: Optional[date] = Query(None),
    date_to: Optional[date] = Query(None),
    min_persistence: float = Query(0.0, ge=0.0, le=1.0),
    limit: int = Query(50, ge=1, le=500),
):
    return _query_hotspots(
        bbox=bbox,
        date_from=date_from,
        date_to=date_to,
        min_persistence=min_persistence,
        limit=limit,
    )


# Plain-callable alias for GraphQL resolvers (backend/api/graphql/schema.py)
# or any other internal caller that needs hotspot data without going through
# FastAPI's request/Query machinery.
get_hotspots_data = _query_hotspots